import React, { useState } from 'react';
import { ActivityIndicator, FlatList, Platform, StatusBar, StyleSheet, Text, TouchableOpacity, View } from 'react-native';
import { Ionicons } from '@expo/vector-icons';
import { useSafeAreaInsets } from 'react-native-safe-area-context';
import Toast from 'react-native-toast-message';
import { khoBtpApi } from '../../services/khoBtpApi';
import { getApiErrorMessage } from '../../services/coreApiClient';
import { BTP_COLORS as COLORS, readValue } from './btpScreenUtils';

export default function KhoBTPReportPackagesScreen({ navigation, route }) {
    const insets = useSafeAreaInsets(); const { product, warehouse } = route.params || {}; const [loading, setLoading] = useState(false); const packages = product?.packages || [];
    const openPackage = async (item) => { const qrCode = readValue(item, ['qrCode', 'QRCode'], ''); if (!qrCode) return Toast.show({ type: 'error', text1: 'Kiện chưa có QR' }); try { setLoading(true); const response = await khoBtpApi.getPackageInfo(qrCode); navigation.navigate('ScannedDetail', { data: response?.data || [], qrCode, kho: warehouse, readOnly: true }); } catch (error) { Toast.show({ type: 'error', text1: 'Không tải được kiện', text2: getApiErrorMessage(error) }); } finally { setLoading(false); } };
    return <View style={styles.container}><StatusBar barStyle="light-content" backgroundColor={COLORS.primary} /><View style={[styles.header, { paddingTop: insets.top + (Platform.OS === 'android' ? 10 : 0) }]}><TouchableOpacity onPress={() => navigation.goBack()}><Ionicons name="arrow-back" size={24} color="#fff" /></TouchableOpacity><Text style={styles.headerTitle} numberOfLines={1}>{product?.itemCode || 'Danh sách kiện'}</Text><View style={{ width: 24 }} /></View>
        <FlatList data={packages} keyExtractor={(item, i) => String(readValue(item, ['idPackage', 'ID_TheKhoKienBTP'], i))} contentContainerStyle={styles.content} ListHeaderComponent={<View style={styles.summary}><Text style={styles.productName}>{product?.productName || 'Bán thành phẩm'}</Text><Text style={styles.summaryText}>{packages.length} kiện • Tổng tồn {product?.totalQuantity || 0}</Text></View>} renderItem={({ item }) => <TouchableOpacity style={styles.card} onPress={() => openPackage(item)}><View style={styles.qrIcon}><Ionicons name="qr-code-outline" size={25} color={COLORS.primary} /></View><View style={styles.body}><Text style={styles.qr} numberOfLines={1}>{readValue(item, ['qrCode', 'QRCode'], '-')}</Text><Text style={styles.meta}>ID kiện: #{readValue(item, ['idPackage', 'ID_TheKhoKienBTP'], '-')}</Text><Text style={styles.meta}>Đơn hàng: {readValue(item, ['maDonHang', 'Ma_DonHang', 'orderId', 'ID_DonHang'], '-')} • Lô: {readValue(item, ['soLoSanXuat', 'So_LoSanXuat', 'productionLotId', 'ID_DonHang_LoSanXuat'], '-')}</Text><Text style={styles.meta}>Dấu tuần: {readValue(item, ['weekMark', 'DauTuan'], '-')}</Text></View><View style={styles.qty}><Text style={styles.qtyValue}>{readValue(item, ['stockQuantity', 'SoLuongTonKien'], 0)}</Text><Text style={styles.qtyLabel}>Tồn</Text></View><Ionicons name="chevron-forward" size={18} color={COLORS.textSecondary} /></TouchableOpacity>} ListEmptyComponent={<Text style={styles.empty}>Không có kiện tồn</Text>} />
        {loading && <View style={styles.loading}><ActivityIndicator size="large" color={COLORS.primary} /></View>}<Toast /></View>;
}
const styles = StyleSheet.create({ container: { flex: 1, backgroundColor: COLORS.background }, header: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', paddingHorizontal: 18, paddingBottom: 16, backgroundColor: COLORS.primary, borderBottomLeftRadius: 24, borderBottomRightRadius: 24 }, headerTitle: { flex: 1, marginHorizontal: 12, textAlign: 'center', color: '#fff', fontSize: 17, fontWeight: '900' }, content: { padding: 16 }, summary: { padding: 16, marginBottom: 15, borderRadius: 17, backgroundColor: '#fff', borderWidth: 1, borderColor: COLORS.border }, productName: { fontSize: 16, fontWeight: '900', color: COLORS.textPrimary }, summaryText: { marginTop: 6, fontSize: 12, fontWeight: '700', color: COLORS.primary }, card: { flexDirection: 'row', alignItems: 'center', gap: 10, padding: 13, marginBottom: 10, backgroundColor: '#fff', borderRadius: 16, borderWidth: 1, borderColor: COLORS.border }, qrIcon: { width: 44, height: 44, borderRadius: 12, alignItems: 'center', justifyContent: 'center', backgroundColor: COLORS.primaryLight }, body: { flex: 1, minWidth: 0 }, qr: { fontSize: 13, fontWeight: '900', color: COLORS.textPrimary }, meta: { marginTop: 4, fontSize: 10, color: COLORS.textSecondary }, qty: { minWidth: 58, padding: 8, alignItems: 'center', backgroundColor: COLORS.primaryLight, borderRadius: 11 }, qtyValue: { color: COLORS.primary, fontSize: 15, fontWeight: '900' }, qtyLabel: { color: COLORS.textSecondary, fontSize: 9 }, empty: { marginTop: 30, textAlign: 'center', color: COLORS.textSecondary }, loading: { ...StyleSheet.absoluteFillObject, alignItems: 'center', justifyContent: 'center', backgroundColor: 'rgba(255,255,255,.5)' } });
